name: Renovate Tidy
on:
  push:
    branches:
      - 'renovate/**/*'
jobs:
  tidy-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        # with:
        #   ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ~1.17

      - name: Tidy up after Renovate
        shell: bash
        run: |
          git show ${GITHUB_SHA} --stat
          echo "******"
          git diff-tree --no-commit-id --name-only -r HEAD
          echo "******"
          git diff-tree --no-commit-id --name-only -r HEAD| grep --color=never go.mod | xargs -0 -I % bash -c 'cd $(dirname %) && go mod tidy -compat=1.17 && cd -;'

      - name: Commit and push
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Run go mod tidy
